gis: main.cpp geoRecord.h BST.h BinNodeT.h  Controller.h FileManager.h Singleton.h prQuadTree.h prQuadLeaf.h prQuadInternal.h prQuadNode.h
	g++ -g -o gis main.cpp geoRecord.cpp Controller.cpp FileManager.cpp
prquad: prQuadTest.cpp geoRecord.h prQuadLeaf.h prQuadTree.h Singleton.h geoRecord.h prQuadInternal.h prQuadNode.h
	g++ -g -o prquad prQuadTest.cpp geoRecord.cpp
