calculator: main.cpp DropOutStackT.h const_iterator.h DListT.h DNodeT.h iterator.h 
	g++ -g -o calculator main.cpp 

dlist1: const_iterator.h DListT.h DNodeT.h iterator.h DlistTest.cpp
	g++ -g -o dlist1 DlistTest.cpp

dlist2: const_iterator.h DListT.h DNodeT.h iterator.h DlistTest2.cpp 
	g++ -g -o dlist2 DlistTest2.cpp

stackt: DropOutStackT.h DropOutStackT.cpp stackTest.cpp
	g++ -g -o stackt stackTest.cpp

stack: DropOutStack.h DropOutStack.cpp item.h stackTest.cpp
	g++ -g -o stack stack_Test.cpp
